feat: реализация 2-го этапа дипломного проекта (Основной сервис)
SmirnovSA1/java-explore-with-me pull request #2
Opened 2024-07-16 18:11 UTC by SmirnovSA1

2024-07-16 20:35 UTC, andrew-larkin requested changes
Привет! Очень хорошо, местами поправить и работа будет принята.

2024-07-16 20:35 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +    Optional<List<Compilation>> findAllByPinned(Boolean pinned, Pageable pageable);
list можно не заворачивать в optional. если элементы не найдутся, просто вернется пустой list

2024-07-16 20:35 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/location/dto/LocationDto.java
> +public class LocationDto {
его хорошо бы использовать и в других dto, где используется модель

2024-07-16 20:35 UTC, andrew-larkin commented on ewm-service/src/main/java/ru/practicum/participation/model/ParticipationRequest.java
> +    private Long event;
должны быть связи с другими таблицами

2024-07-17 11:54 UTC, SmirnovSA1 commented on ewm-service/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +    Optional<List<Compilation>> findAllByPinned(Boolean pinned, Pageable pageable);
Исправил

2024-07-17 11:54 UTC, SmirnovSA1 commented on ewm-service/src/main/java/ru/practicum/location/dto/LocationDto.java
> +public class LocationDto {
Исправил

2024-07-17 11:54 UTC, SmirnovSA1 commented on ewm-service/src/main/java/ru/practicum/participation/model/ParticipationRequest.java
> +    private Long event;
связи с другими таблицами есть, например requester_id связан с таблицей users по user_id

2024-07-17 19:06 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-07-17 21:26 UTC, merged